#!/bin/sh

set -e

case "${1}" in
	configure)
	if [ ! -f "/usr/share/backgrounds/default_background.jpg" ]; then
	    mkdir -p /usr/share/backgrounds/
	    update-alternatives --install /usr/share/backgrounds/default_background.jpg \
		    deepin-default-background /usr/share/wallpapers/deepin/desktop.jpg 50
	fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		;;
esac
exit 0
